//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Appliocation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LoginSingup
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "First Name Required")]
        [StringLength(10, MinimumLength = 3, ErrorMessage = "Name should be at least 3 to 10 charachters")]
        [DataType(DataType.Text)]
        public string First_Nam { get; set; }


        [Required(ErrorMessage = "First Name Required")]
        [StringLength(10, MinimumLength = 3, ErrorMessage = "Name should be at least 3 to 10 charachters")]
        [DataType(DataType.Text)]
        public string Last_Name { get; set; }

        [Required(ErrorMessage = "Gender Required")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "Email Required")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Username Required")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Password Required")]
        [DataType(DataType.Password)]
        [StringLength(8, ErrorMessage = "PAssword should be  required 8 charachters")]
        public string Password { get; set; }
        [StringLength(8, ErrorMessage = "PAssword should be  required 8 charachters")]
        [Required(ErrorMessage = "Password Required")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string Re_Paassword { get; set; }
    }
}
