//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Appliocation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Tbl_Student
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Name Required")]
        [StringLength(18, MinimumLength = 3, ErrorMessage = "Name should be at least 3 to 18 charachters")]
        [DataType(DataType.Text)]
        public string Name { get; set; }

        [DisplayName("Father Name")]
        [Required(ErrorMessage = "Name Required")]
        [StringLength(18, MinimumLength = 3, ErrorMessage = "Name should be at least 3 to 8 charachters")]
        [DataType(DataType.Text)]
        public string F_Name { get; set; }

        [Required(ErrorMessage = "Gender Required")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "Age Required")]
        public Nullable<int> Age { get; set; }

        [DisplayName("Date of Birth")]
        [Required(ErrorMessage = "Date of Birth Required")]
        [DataType(DataType.Date)]
        public string DOB { get; set; }

        [Required(ErrorMessage = "Attendence Required")]
        public Nullable<int> Attendence { get; set; }

        [DisplayName("Image")]
        public string Image_Name { get; set; }

        public HttpPostedFileBase Imagefile { get; set; }
    }
}
